/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Apresentação;

import ControleAlunos.ControleAlunos;
import Dados.Aluno;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Lohran
 */
public class Principal extends javax.swing.JFrame {

    LinkedList<Aluno> aluno = new LinkedList<>();

    ControleAlunos ca = new ControleAlunos();

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tdfNome = new javax.swing.JTextField();
        tdfMat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tdfIdade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        bntVer = new javax.swing.JButton();
        btnQalunos = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        tdfData = new javax.swing.JFormattedTextField();
        tdfTel = new javax.swing.JFormattedTextField();
        tdfCPF = new javax.swing.JFormattedTextField();
        btnMatPriUlt = new javax.swing.JButton();
        btnNovoVelho = new javax.swing.JButton();
        btnTerceiro = new javax.swing.JButton();
        btnVerifica = new javax.swing.JButton();
        btnRemoveUlt = new javax.swing.JButton();
        btnTerElemento = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnDupla = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 67, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Matricula");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        tdfNome.setActionCommand("<Not Set>");
        tdfNome.setNextFocusableComponent(tdfMat);
        getContentPane().add(tdfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 320, -1));

        tdfMat.setNextFocusableComponent(tdfTel);
        getContentPane().add(tdfMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 320, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Idade");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(tdfIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 320, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CPF");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de Nascimento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        btnSair.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 140, -1));

        btnSalvar.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnSalvar.setText("Adicionar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 110, -1));

        bntVer.setFont(new java.awt.Font("Segoe UI Black", 3, 10)); // NOI18N
        bntVer.setText("Ver Todos");
        bntVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVerActionPerformed(evt);
            }
        });
        getContentPane().add(bntVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 180, -1));

        btnQalunos.setFont(new java.awt.Font("Segoe UI Black", 3, 10)); // NOI18N
        btnQalunos.setText("Quantidade de Alunos");
        btnQalunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQalunosActionPerformed(evt);
            }
        });
        getContentPane().add(btnQalunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 190, -1));

        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 112, -1));

        btnRemove.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 100, -1));

        try {
            tdfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tdfData.setNextFocusableComponent(btnSalvar);
        tdfData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdfDataActionPerformed(evt);
            }
        });
        getContentPane().add(tdfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 320, -1));

        try {
            tdfTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tdfTel.setNextFocusableComponent(tdfIdade);
        getContentPane().add(tdfTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 320, -1));

        try {
            tdfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tdfCPF.setNextFocusableComponent(tdfData);
        tdfCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdfCPFActionPerformed(evt);
            }
        });
        getContentPane().add(tdfCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 320, -1));

        btnMatPriUlt.setFont(new java.awt.Font("Segoe UI Black", 3, 10)); // NOI18N
        btnMatPriUlt.setText("Matrícula do Primeiro e Último");
        btnMatPriUlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatPriUltActionPerformed(evt);
            }
        });
        getContentPane().add(btnMatPriUlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 190, -1));

        btnNovoVelho.setFont(new java.awt.Font("Segoe UI Black", 3, 10)); // NOI18N
        btnNovoVelho.setText("Mais Novo e Mais Velho");
        btnNovoVelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoVelhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovoVelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 180, -1));

        btnTerceiro.setFont(new java.awt.Font("Segoe UI Black", 3, 10)); // NOI18N
        btnTerceiro.setText("Imprimir o Terceiro Elemento");
        btnTerceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerceiroActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 180, -1));

        btnVerifica.setFont(new java.awt.Font("Segoe UI Black", 3, 10)); // NOI18N
        btnVerifica.setText("Verificar");
        btnVerifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 190, -1));

        btnRemoveUlt.setFont(new java.awt.Font("Segoe UI Black", 3, 10)); // NOI18N
        btnRemoveUlt.setText("Remover Último");
        btnRemoveUlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUltActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveUlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 180, -1));

        btnTerElemento.setFont(new java.awt.Font("Segoe UI Black", 3, 10)); // NOI18N
        btnTerElemento.setText("Inserir o Terceiro Elemento");
        btnTerElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerElementoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 190, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Matrícula Online");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jButton1.setText("Salvar em Arquivo CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 240, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apresentação/Imagens/download (1).png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        btnDupla.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnDupla.setText("Dupla");
        btnDupla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuplaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDupla, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 80, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apresentação/Imagens/Plano de Fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ArrayList<Aluno> aln = ca.retornarTodos();
        Aluno a = new Aluno();
        a.setNome(tdfNome.getText());
        a.setMatricula(tdfMat.getText());
        a.setTelefone(tdfTel.getText());
        a.setIdade(tdfIdade.getText());
        a.setCPF(tdfCPF.getText());
        String s = tdfData.getText();
        try {
            a.setData(s);
        } catch (ParseException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (aln.isEmpty()) {
            ca.salvar(a);
            JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso.");
            tdfNome.setText("");
            tdfMat.setText("");
            tdfTel.setText("");
            tdfIdade.setText("");
            tdfCPF.setText("");
            tdfData.setText("");
            tdfNome.requestFocus();
        } else {
            for (int i = 0; i < aln.size() && aln.get(i) != null; i++) {
                String x = tdfMat.getText();
                if (x.equals("")) {
                    JOptionPane.showMessageDialog(null, "Matricula inválida.");
                    tdfMat.requestFocus();
                    break;
                } else {
                    if (aln.size() == 1) {
                        if (aln.get(0).getMatricula().equals(x)) {
                            JOptionPane.showMessageDialog(null, "Matricula já cadastrada.");
                            tdfMat.setText("");
                            tdfMat.requestFocus();
                            break;
                        } else {
                            ca.salvar(a);
                            JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso.");
                            tdfNome.setText("");
                            tdfMat.setText("");
                            tdfTel.setText("");
                            tdfIdade.setText("");
                            tdfCPF.setText("");
                            tdfData.setText("");
                            tdfNome.requestFocus();
                            break;
                        }
                    }
                    if (aln.size() > 1) {
                        if (aln.get(0).getMatricula().equals(x)) {
                            JOptionPane.showMessageDialog(null, "Matricula já cadastrada.");
                            tdfMat.setText("");
                            tdfMat.requestFocus();
                            break;
                        } else {
                            if (ca.matriculaD(x, ca)) {
                                JOptionPane.showMessageDialog(null, "Matricula já cadastrada.");
                                tdfMat.setText("");
                                tdfMat.requestFocus();
                                break;
                            } else {
                                ca.salvar(a);
                                JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso.");
                                tdfNome.setText("");
                                tdfMat.setText("");
                                tdfTel.setText("");
                                tdfIdade.setText("");
                                tdfCPF.setText("");
                                tdfData.setText("");
                                tdfNome.requestFocus();
                                break;
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void bntVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVerActionPerformed
        TelaDi td = new TelaDi(null, true, ca);
        td.setVisible(true);
    }//GEN-LAST:event_bntVerActionPerformed

    private void btnQalunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQalunosActionPerformed
        int quantidadeAlunos = ca.quantidadeAlunos();
        JOptionPane.showMessageDialog(null, "Quantidade de Alunos: " + quantidadeAlunos);
    }//GEN-LAST:event_btnQalunosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Display dp = new Display(null, true, ca);
        dp.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMatPriUltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatPriUltActionPerformed
        ArrayList<Aluno> al = ca.retornarTodos();
        int i = (al.size() - 1);
        JOptionPane.showMessageDialog(null, "Matricula Primeiro: " + al.get(0).getMatricula() + "\n\nMatricula Ultimo: " + al.get(i).getMatricula());
    }//GEN-LAST:event_btnMatPriUltActionPerformed

    private void btnTerceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerceiroActionPerformed
        TelaT tt = new TelaT(null, true, ca);
        tt.setVisible(true);
    }//GEN-LAST:event_btnTerceiroActionPerformed

    private void btnNovoVelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoVelhoActionPerformed
        ArrayList<Aluno> al = ca.retornarTodos();

        int n;
        n = ca.maisNovo();
        int v;
        v = ca.maisVelho(0);

        JOptionPane.showMessageDialog(null, "Aluno mais novo: " + al.get(n).getNome() + "\n\nAluno mais velho: " + al.get(v).getNome());

    }//GEN-LAST:event_btnNovoVelhoActionPerformed

    private void btnRemoveUltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUltActionPerformed
        ArrayList<Aluno> al = ca.retornarTodos();

        int n = (al.size() - 1);

        al.remove(n);

        JOptionPane.showMessageDialog(null, "Aluno excluído.");

    }//GEN-LAST:event_btnRemoveUltActionPerformed

    private void btnVerificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificaActionPerformed
        TelaV tv = new TelaV(null, true, ca);
        tv.setVisible(true);
    }//GEN-LAST:event_btnVerificaActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        TelaRemove tr = new TelaRemove(null, true, ca);
        tr.setVisible(true);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void tdfDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdfDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdfDataActionPerformed

    private void btnTerElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerElementoActionPerformed
        JOptionPane.showMessageDialog(null, "Esse método exige dois ou mais elementos adicionados.");
        TelaTres tr = new TelaTres(null, true, ca);
        tr.setVisible(true);
    }//GEN-LAST:event_btnTerElementoActionPerformed

    private void tdfCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdfCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdfCPFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser selecionarArquivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Arquivos csv", "csv");
        selecionarArquivo.setFileFilter(filtro);

        int selecionar = selecionarArquivo.showOpenDialog(this);

        if (selecionar == JFileChooser.APPROVE_OPTION) {
            File arquivo = selecionarArquivo.getSelectedFile();
            guardarArquivo(arquivo);
        }

    }

    public void guardarArquivo(File arquivo) {
        FileWriter ficheiro = null;
        PrintWriter pw = null;
        ArrayList<Aluno> a = ca.retornarTodos();

        try {
            ficheiro = new FileWriter(arquivo);
            pw = new PrintWriter(ficheiro);

            for (int i = 0; i < a.size() && a.get(i) != null; i++) {
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                String linha = a.get(i).getMatricula() + ", " + a.get(i).getNome() + ", " + a.get(i).getTelefone() + ", " + a.get(i).getCPF() + ", " + a.get(i).getIdade() + ", " + formato.format(a.get(i).getData());
                pw.println(linha);
            }

        } catch (Exception ex) {
            ex.printStackTrace();

        } finally {
            try {
                if (ficheiro != null) {
                    ficheiro.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDuplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuplaActionPerformed
        JOptionPane.showMessageDialog(null, " Cristian Gabriel Pinho Cunha \n Lohran Francisco Mendes Medeiros");
    }//GEN-LAST:event_btnDuplaActionPerformed
    public void carregarArquivo(File arquivo) {
        FileReader fr = null;
        BufferedReader br = null;

        try {
            fr = new FileReader(arquivo);
            br = new BufferedReader(fr);

            String linha;
            while ((linha = br.readLine()) != null) {

                Aluno a = new Aluno();
                String arranjo[] = linha.split(",");
                if (arranjo.length >= 1) {
                    a.setMatricula(arranjo[0]);
                    a.setNome(arranjo[1]);
                    a.setTelefone(arranjo[2]);
                    a.setCPF(arranjo[3]);
                    a.setIdade(arranjo[4]);
                    a.setData(arranjo[5]);
                    aluno.add(a);

                }
            }
            TelaDi tela = new TelaDi(null, true, ca);
            tela.exibeInformacoes();

        } catch (Exception ex) {
            ex.printStackTrace();

        } finally {
            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVer;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDupla;
    private javax.swing.JButton btnMatPriUlt;
    private javax.swing.JButton btnNovoVelho;
    private javax.swing.JButton btnQalunos;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRemoveUlt;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnTerElemento;
    private javax.swing.JButton btnTerceiro;
    private javax.swing.JButton btnVerifica;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField tdfCPF;
    private javax.swing.JFormattedTextField tdfData;
    private javax.swing.JTextField tdfIdade;
    private javax.swing.JTextField tdfMat;
    private javax.swing.JTextField tdfNome;
    private javax.swing.JFormattedTextField tdfTel;
    // End of variables declaration//GEN-END:variables
}
